site_name: Cube Alchemy
#repo_url: https://github.com/cube-alchemy/cube-alchemy
#repo_name: Cube Alchemy

theme:
  name: material
  logo: assets/cube-alchemy-logo.png
  favicon: assets/cube-alchemy-logo.png
  features:
    - navigation.expand
    - navigation.sections
    - navigation.top
    - toc.integrate
    - content.code.copy
  icon:
    repo: fontawesome/brands/github

extra_css:
  - customstyle.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/cube-alchemy/cube-alchemy
    - icon: material/email
      link: mailto:delmontejuan92@gmail.com
    - icon: fontawesome/regular/house
      link: https://cube-alchemy.com

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
nav:
  - Home: index.md
  - Overview: overview.md
  - Installation: installation.md
  - Concepts:
    - Hypercube: concepts/hypercube.md
    - Workflow: concepts/workflow.md
    - Relationships: concepts/relationships.md
    - Dimensions: concepts/dimensions.md
    - Metrics: concepts/metrics.md
    - Queries: concepts/queries.md
    - Filters: concepts/filters.md
    - Context State: concepts/context-state.md
    - Plotting: concepts/plotting.md
    - Model Catalog: concepts/model_catalog.md
  - API:
    - Hypercube: api/hypercube.md
    - Metrics: api/metric_methods.md
    - Queries: api/query_methods.md
    - Analytics Specs: api/analytics_specs.md
    - Filters: api/filter_methods.md
    - Plotting System: api/plotting_system.md
    - Model Catalog: api/model_catalog.md
  - Examples: examples.md
  - Streamlit Integration: streamlit.md
  - Contributing: contributing.md

extra_javascript:
  - https://www.googletagmanager.com/gtag/js?id=G-JXW3ZYFYK0
  - js/ga4.js

